# Generated by Django 4.1.7 on 2023-04-03 21:12

from django.contrib.postgres.operations import CreateExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [CreateExtension(name="fuzzystrmatch")]
