version: "3.3"

services:
  calendr_api:
    build:
      context: ./backend
    container_name: calendr_api
    depends_on:
      - calendr_db
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env.dev

  calendr_worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: calendr_worker
    entrypoint: ./entrypoint.worker.sh
    depends_on:
      - calendr_api
      - calendr_db
      - calendr_redis
    command: celery -A calendr worker -l info
    volumes:
      - ./backend:/usr/src/app/
    env_file:
      - ./backend/.env.dev

  calendr_db:
    container_name: calendr_db
    image: postgres:15.2-alpine
    volumes:
      - calendr_postgres:/var/lib/postgresql/data/
    ports:
      - 2345:5432
    environment:
      - POSTGRES_USER=calendr
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=calendr

  calendr_redis:
    container_name: calendr_redis
    image: redis:7.0.9-alpine
    volumes:
      - calendr_redis:/var/lib/redis/data/
    ports:
      - 6379:6379

volumes:
  calendr_postgres:
  calendr_redis:
