version: "3.3"

services:
  psico_api:
    build:
      context: ./backend
    container_name: psico_api
    depends_on:
      - psico_db
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env.dev

  psico_worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: psico_worker
    entrypoint: ./entrypoint.worker.sh
    depends_on:
      - psico_api
      - psico_db
      - psico_redis
    command: celery -A app worker -l info
    volumes:
      - ./backend:/usr/src/app/
    env_file:
      - ./backend/.env.dev

  psico_db:
    container_name: psico_db
    image: postgres:15.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 2345:5432
    environment:
      - POSTGRES_USER=psico
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=psico

  psico_redis:
    container_name: psico_redis
    image: redis:7.0.9-alpine
    volumes:
      - psico_redis:/var/lib/redis/data/
    ports:
      - 6379:6379

volumes:
  postgres_data:
  psico_redis:
