version: "3.3"

services:
  api_app:
    build:
      context: ./backend
    container_name: api_app
    depends_on:
      - db_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env.dev

  db_app:
    container_name: db_app
    image: postgres:15.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 2345:5432
    environment:
      - POSTGRES_USER=psico
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=psico

volumes:
  postgres_data:
