from django.db import models


class StateChoices(models.TextChoices):
    AC = "AC", "Acre",
    AL = "AL", "Alagoas",
    AP = "AP", "Amapá",
    AM = "AM", "Amapá",
    BA = "BA", "Bahia",
    CE = "CE", "Ceará",
    DF = "DF", "Distrito Federal",
    ES = "ES", "Espirito Santo",
    GO = "GO", "Goiás",
    MA = "MA", "Maranhão",
    MS = "MS", "Mato Grosso do Sul",
    MT = "MT", "Mato Grosso",
    MG = "MG", "Minas Gerais",
    PA = "PA", "Pará",
    PB = "PB", "Paraíba",
    PR = "PR", "Paraná",
    PE = "PE", "Pernambuco",
    PI = "PI", "Piauí",
    RJ = "RJ", "Rio de Janeiro",
    RS = "RS", "Rio Grande do Sul",
    RO = "RO", "Rondônia",
    RR = "RR", "Roraima",
    SC = "SC", "Santa Catarina",
    SP = "SP", "São Paulo",
    SE = "SE", "Sergipe",
    TO = "TO", "Tocantins",
