from .appointment import AppointmentViewSet
from .calendar import CalendarViewSet
from .city import CityViewSet
from .logged_user import LoggedUserView
from .patient import PatientViewSet
from .period import PeriodViewSet
from .plan import PlanViewSet
from .profession import ProfessionViewSet
from .profile import ProfileViewSet
from .signup import SignUpViewSet
