from .city import CityViewSet
from .logged_user import LoggedUserView
from .patient.appointment import PatientAppointmentViewSet
from .patient.calendar import PatientCalendarViewSet
from .plan import PlanViewSet
from .profession import ProfessionViewSet
from .professional.appointment import ProfessionalAppointmentViewSet
from .professional.patient import ProfessionalPatientViewSet
from .professional.slot import ProfessionalSlotViewSet
from .profile import ProfileViewSet
from .signup import SignUpViewSet
from .tester import TestViewSet
