from .appointment import AppointmentViewSet
from .city import CityViewSet
from .log import LogViewSet
from .logged_user import LoggedUserView
from .nested.nested_calendar import NestedCalendarViewSet
from .patient import PatientViewSet
from .plan import PlanViewSet
from .profession import ProfessionViewSet
from .profile import ProfileViewSet
from .signup import SignUpViewSet
from .slot import SlotViewSet
